# Generated by Django 3.2.9 on 2021-12-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_good_hands', '0003_auto_20211204_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.IntegerField(blank=True, help_text='Contact phone number'),
        ),
    ]
